[FIX] contract_sale_generation: Sale line violates check constraint
Steps:
1. Create a contract with "Sale" generation type
2. Add a line without a product
3. Generate a sale from the contract

Before this change:
The sale cannot be created because it raises:
> ValueError: <class 'psycopg2.errors.CheckViolation'>: "new row for relation "sale_order_line" violates check constraint "sale_order_line_accountable_required_fields"

After this change:
The line must have a product in order to save the contract.